apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lyker
spec:
  project: default
  source:
    repoURL: https://github.com/onai254/Lyker.git
    path: Kubernetes
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "apps"
      kind: "Deployment"
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/template/metadata/labels
    - group: "apps"
      kind: "StatefulSet"
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/template/metadata/labels
